baseURL = 'https://openhealth5g.org/'
languageCode = 'en-us'
title = 'OpenHealth5G'

[params]
  description = 'Open 5G Networking for Digital Health'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20
  [[menu.main]]
    identifier = "use-cases"
    name = "Use Cases"
    pageRef = "/use-cases"
    weight = 30
  [[menu.main]]
    identifier = "partners"
    name = "Partners"
    pageRef = "/partners"
    weight = 40
  [[menu.main]]
    identifier = "team"
    name = "Team"
    pageRef = "/team"
    weight = 45
  [[menu.main]]
    identifier = "software"
    name = "Software"
    pageRef = "/software"
    weight = 50
  [[menu.main]]
    identifier = "news"
    name = "News"
    pageRef = "/news"
    weight = 60
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    pageRef = "/publications"
    weight = 70

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
